copy *.frm "C:\Documents and Settings\wifi\Mis documentos\Dropbox\WGestionDEV"
copy *.bas "C:\Documents and Settings\wifi\Mis documentos\Dropbox\WGestionDEV"
copy *.dca "C:\Documents and Settings\wifi\Mis documentos\Dropbox\WGestionDEV"
copy *.crt "C:\Documents and Settings\wifi\Mis documentos\Dropbox\WGestionDEV"
copy *.dsr "C:\Documents and Settings\wifi\Mis documentos\Dropbox\WGestionDEV"
copy *.dsx "C:\Documents and Settings\wifi\Mis documentos\Dropbox\WGestionDEV"
copy *.vbp "C:\Documents and Settings\wifi\Mis documentos\Dropbox\WGestionDEV"
copy *.xml "C:\Documents and Settings\wifi\Mis documentos\Dropbox\WGestionDEV"
